🚀🚀  support aria2 multi-thread download now. (Related issue: #5)

diff --git a/AvgleDownloader b/AvgleDownloader
--- a/AvgleDownloader
+++ b/AvgleDownloader
@@ -17,6 +17,10 @@ HTTP_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (K
 # wget binary file
 # it will be a path to a binary file in `windows-libs` directory if this script is running in git bash
 WGET_BIN="wget";
+ARIA2C_BIN="aria2c";
+DOWNLOADER_TYPE="wget"; # or equals aria2c
+
+DOWNLOAD_LOG="avgle-download.log";
 
 #================================
 #====   Colorized variables  ====
@@ -34,6 +38,7 @@ if [[ -t 1 ]]; then # is terminal?
 		GREEN_BOLD="\x1b[1;32m";
 		BLUE="\x1b[0;34m";
 		BLUE_BOLD="\x1b[1;34m";
+		CYAN_BOLD="\x1b[1;36m";
 		GREY="\x1b[37m";
 	fi
 fi
@@ -58,26 +63,55 @@ function error() { echo -e "${RED_BOLD}  error: ${RED}$1${RESET}\n"; exit 1; }
 #===================================
 #=======  Network functions  =======
 
+function _download() {
+	if [[ "$DOWNLOADER_TYPE" == "$ARIA2C_BIN" ]]; then
+		[[ -f "$DOWNLOAD_LOG" ]] && rm "$DOWNLOAD_LOG";
+
+		[[ "$1" == with_referer ]] && referer="--referer=$HTTP_REFERER";
+		gawk -vout_name="$3" '{
+			if (NF==1 && out_name) {
+				print $1;
+				print "  out=" out_name;
+			} else {
+				for (i=1;i<=NF;i++) {
+					print $i;
+					out_name = $i;
+					gsub(/^.*\//, "", out_name);
+					print "  out=" out_name;
+				}
+			}
+		}' <<< "$2" |
+			"$ARIA2C_BIN" "$referer" --user-agent="$HTTP_USER_AGENT" \
+				--show-files --continue=true \
+				--input-file=- \
+				--log="$DOWNLOAD_LOG" --log-level=info;
+	else
+		if [[ "$1" == with_referer ]]; then ref1="--header"; ref2="Referer: $HTTP_REFERER"; fi
+		if [[ -n "$3" ]]; then  out1="-O"; out2="$3"; fi
+		"$WGET_BIN" "$ref1" "$ref2" --header "User-Agent: $HTTP_USER_AGENT" "$out1" "$out2" $2;
+	fi
+}
+
 # $1: description
 # $2: url
 # $3: [Optional] target file
 function better_wget() {
 	local download_ok=true;
 
-	local extra_opts="";
-	[[ -n "$3" ]] && extra_opts="-O $3";
-
 	if [[ $ENABLE_REFERER == true ]]; then
-		"$WGET_BIN" --header "Referer: $HTTP_REFERER" --header "User-Agent: $HTTP_USER_AGENT" \
-			$2 $extra_opts || download_ok=false;
+		_download with_referer "$2" "$3" || download_ok=false;
 
 		if [[ $download_ok != true ]]; then
+			# has download log but there has no mark of 403, just exit
+			if [[ -f "$DOWNLOAD_LOG" ]] && [[ -z "$(grep -e "HTTP/1.1 403 Forbidden" "$DOWNLOAD_LOG")" ]]; then
+				error "Could not download $1 (log: $DOWNLOAD_LOG)";
+			fi
 			warn "execute wget with 'Referer' header failed! (trying to execute again without 'Referer' header)";
 			ENABLE_REFERER=false;
-			"$WGET_BIN" --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
+			_download no_referer "$2" "$3" || error "Could not download $1";
 		fi
 	else
-		"$WGET_BIN" --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
+		_download no_referer "$2" "$3" || error "Could not download $1 (log: $DOWNLOAD_LOG)";
 	fi
 }
 
@@ -95,7 +129,7 @@ echo -e ' | | | |/ _ \ \ /\ / / '\''_ \| |/ _ \ / _` |/ _` |/ _ \ '\''__|'
 echo -e ' | |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   '
 echo -e ' |____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   '
 echo -e ''
-echo -e '            Update date: 2018-10-30'
+echo -e '            Update date: 2018-11-22'
 echo -e ''
 echo -e "${BOLD} Usage: AvgleDownloader <video-name> <m3u8-url-base64>${RESET}"
 echo -e ''
@@ -114,7 +148,12 @@ fi
 [[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
 
 WHICH_WGET="$(which "$WGET_BIN" 2>/dev/null)"
-if [[ -z "$WHICH_WGET" ]]; then
+WHICH_ARIA2C="$(which "$ARIA2C_BIN" 2>/dev/null)"
+if [[ -n "$WHICH_ARIA2C" ]]; then
+	DOWNLOADER_TYPE="aria2c";
+	echo -e "${CYAN_BOLD}Experimental improvement: use \"aria2c\" instead of \"wget\"";
+	echo -e "      🚀  use aria2c will be faster than wget 🚀${RESET}"
+elif [[ -z "$WHICH_WGET" ]]; then
 	if [[ $WIN_USER == true ]]; then
 		__DIRNAME="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)";
 
@@ -180,12 +219,15 @@ MISSING_FILE_COUNT=0;
 for (( i=1 ; i<=$LAST_FRAGMENT_ID ; i++ )); do
 	DOWNLOAD_TO="seg-${i}-v1-a1.ts"
 	if [[ -e "${DOWNLOAD_TO}" ]]; then
-		SIZE=$(stat --printf="%s" "${DOWNLOAD_TO}");
-		if [[ $SIZE -lt 10240 ]]; then # less than 10k (is broken or download failed)
-			rm "${DOWNLOAD_TO}" || error "could not delete broken file \"${DOWNLOAD_TO}\"";
-			warn "cleaned broken downloaded file: \"${DOWNLOAD_TO}\"";
-		else
-			continue;
+		# there has aria2 continue download mark file
+		if [[ ! -e "${DOWNLOAD_TO}.aria2" ]] || [[ "$DOWNLOADER_TYPE" != "$ARIA2C_BIN" ]]; then
+			SIZE=$(stat --printf="%s" "${DOWNLOAD_TO}");
+			if [[ $SIZE -lt 10240 ]]; then # less than 10k (is broken or download failed)
+				rm "${DOWNLOAD_TO}" || error "could not delete broken file \"${DOWNLOAD_TO}\"";
+				warn "cleaned broken downloaded file: \"${DOWNLOAD_TO}\"";
+			else
+				continue;
+			fi
 		fi
 	fi
 	MISSING_FILE="${MISSING_FILE}${i}\n";
