support Windows (Git Bash or CygWin).
related issue: #6

diff --git a/Avgle b/Avgle
--- a/Avgle
+++ b/Avgle
@@ -5,6 +5,10 @@ M3U8_FILE="${DIR_NAME}.m3u8"
 LIST_FILE="concat.list"
 TARGET_FILE="../${DIR_NAME}.mp4"
 
+# ffmpeg binary file
+# it will be a path to a binary file in `windows-libs` directory if this script is running in git bash
+FFMPEG_BIN="ffmpeg";
+
 #================================
 #====   Colorized variables  ====
 if [[ -t 1 ]]; then # is terminal?
@@ -56,7 +60,7 @@ echo -e ' /_/    \_\_/ \__, |_|\___|'
 echo -e '               __/ |       '
 echo -e '              |___/        '
 echo -e ''
-echo -e '            Update date: 2018-10-23'
+echo -e '            Update date: 2018-10-27'
 echo -e ''
 echo -e "${BOLD} 1.Concat seg-*-v1-a1.ts you downloaded from avgle"
 echo -e "${BOLD} 2.Convert ts file to mp4 using ffmpeg"
@@ -65,10 +69,33 @@ echo -e "${BOLD} 4.Remove All temporary *.ts files if you don't need them anymor
 echo -e "${DIV_LINE}\n"
 
 # ===========================
+# Windows User
+WIN_USER=false
+UNAME_S="$(uname -s)";
+if [[ "$UNAME_S" == MINGW* ]] || [[ "$UNAME_S" == CYGWIN* ]]; then
+	WIN_USER=true;
+fi
+
+# ===========================
 # Checking dependencies
-[[ -z `which ffmpeg` ]] && error "\"ffmpeg\" is missing! (Ubuntu: sudo apt install ffmpeg)";
 [[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
 [[ -z `which sed` ]] && error "\"sed\" is missing! (Ubuntu: sudo apt install sed)";
+if [[ -z `which "$FFMPEG_BIN"` ]]; then
+	if [[ $WIN_USER == true ]]; then
+		__DIRNAME="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)";
+
+		pushd "$__DIRNAME" > /dev/null || error "goto script directory failed!";
+		FFMPEG_BIN="$(find windows-libs -type f -name "ffmpeg.exe" | head -n1)";
+		if [[ -z "$FFMPEG_BIN" ]]; then
+			FIX_IT="(How to fix this error: read windows-libs/README.md)"
+			error "ffmpeg.exe is missng in directory \"windows-libs\". $FIX_IT";
+		fi
+		FFMPEG_BIN="$__DIRNAME/$FFMPEG_BIN";
+		popd;
+	else
+		error "\"$FFMPEG_BIN\" is missing! (Ubuntu: sudo apt install $FFMPEG_BIN)";
+	fi
+fi
 
 # ===========================
 # Checking path
@@ -141,7 +168,7 @@ fi
 # aac_adtstoasc: https://ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc
 #   Convert MPEG-2/4 AAC ADTS to an MPEG-4 Audio Specific Configuration bitstream.
 #   Reference from repo: https://github.com/mywarr/chrome-avgle-helper
-ffmpeg -f concat -i "${LIST_FILE}" -bsf:a aac_adtstoasc -c copy "${TARGET_FILE}" -loglevel error \
+"$FFMPEG_BIN" -f concat -i "${LIST_FILE}" -bsf:a aac_adtstoasc -c copy "${TARGET_FILE}" -loglevel error \
 	|| error "ffmpeg convert response exception!"
 title "Converted ${LIST_FILE} file to ${TARGET_FILE}";
 
diff --git a/AvgleDownloader b/AvgleDownloader
--- a/AvgleDownloader
+++ b/AvgleDownloader
@@ -14,6 +14,10 @@ ENABLE_REFERER=true
 # https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
 HTTP_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36";
 
+# wget binary file
+# it will be a path to a binary file in `windows-libs` directory if this script is running in git bash
+WGET_BIN="wget";
+
 #================================
 #====   Colorized variables  ====
 if [[ -t 1 ]]; then # is terminal?
@@ -64,16 +68,16 @@ function better_wget() {
 	[[ -n "$3" ]] && extra_opts="-O $3";
 
 	if [[ $ENABLE_REFERER == true ]]; then
-		wget --header "Referer: $HTTP_REFERER" --header "User-Agent: $HTTP_USER_AGENT" \
+		"$WGET_BIN" --header "Referer: $HTTP_REFERER" --header "User-Agent: $HTTP_USER_AGENT" \
 			$2 $extra_opts || download_ok=false;
 
 		if [[ $download_ok != true ]]; then
 			warn "execute wget with 'Referer' header failed! (trying to execute again without 'Referer' header)";
 			ENABLE_REFERER=false;
-			wget --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
+			"$WGET_BIN" --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
 		fi
 	else
-		wget --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
+		"$WGET_BIN" --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
 	fi
 }
 
@@ -91,16 +95,39 @@ echo -e ' | | | |/ _ \ \ /\ / / '\''_ \| |/ _ \ / _` |/ _` |/ _ \ '\''__|'
 echo -e ' | |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   '
 echo -e ' |____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   '
 echo -e ''
-echo -e '            Update date: 2018-10-12'
+echo -e '            Update date: 2018-10-27'
 echo -e ''
 echo -e "${BOLD} Usage: AvgleDownloader <video-name> <m3u8-url-base64>${RESET}"
 echo -e ''
 echo -e "${DIV_LINE}\n"
 
 # ===========================
+# Windows User
+WIN_USER=false
+UNAME_S="$(uname -s)";
+if [[ "$UNAME_S" == MINGW* ]] || [[ "$UNAME_S" == CYGWIN* ]]; then
+	WIN_USER=true;
+fi
+
+# ===========================
 # Checking dependencies
-[[ -z `which wget` ]] && error "\"wget\" is missing! (Ubuntu: sudo apt install wget)";
 [[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
+if [[ -z `which "$WGET_BIN"` ]]; then
+	if [[ $WIN_USER == true ]]; then
+		__DIRNAME="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)";
+
+		pushd "$__DIRNAME" > /dev/null || error "goto script directory failed!";
+		WGET_BIN="$(find windows-libs -type f -name "wget.exe" | head -n1)";
+		if [[ -z "$WGET_BIN" ]]; then
+			FIX_IT="(How to fix this error: read windows-libs/README.md)"
+			error "wget.exe is missng in directory \"windows-libs\". $FIX_IT";
+		fi
+		WGET_BIN="$__DIRNAME/$WGET_BIN";
+		popd;
+	else
+		error "\"$WGET_BIN\" is missing! (Ubuntu: sudo apt install $WGET_BIN)";
+	fi
+fi
 
 # ===========================
 # Checking arguments
