add editorconfig. refactory combiner script

diff --git a/Avgle b/Avgle
--- a/Avgle
+++ b/Avgle
@@ -1,42 +1,47 @@
 #!/usr/bin/env bash
 
-ALL_IN_ONE_TS_FILE="av.ts"
+TEMP_FILE="tmp.ts"
 DIR_NAME=$(basename `pwd`)
 TARGET_FILE="../${DIR_NAME}.mp4"
 
 #================================
 #====   Colorized variables  ====
-RED="\e[0;31m"
-RED_BOLD="\e[1;31m"
-YELLOW_BOLD="\e[1;33m"
-GREEN="\e[0;32m"
-GREEN_BOLD="\e[1;32m"
-BLUE="\e[0;34m"
-BLUE_BOLD="\e[1;34m"
-BOLD="\e[1m"
-RESET="\e[0m"
+if [[ -t 1 ]]; then # is terminal?
+	COLOR_MODE=`tput colors`;
+	if [[ -n "$COLOR_MODE" ]] && [[ "$COLOR_MODE" -ge 8 ]]; then
+		BOLD="\x1b[1m";
+		RESET="\x1b[0m";
+
+		RED="\x1b[0;31m";
+		RED_BOLD="\x1b[1;31m";
+		YELLOW_BOLD="\x1b[1;33m";
+		GREEN="\x1b[0;32m";
+		GREEN_BOLD="\x1b[1;32m";
+		BLUE="\x1b[0;34m";
+		BLUE_BOLD="\x1b[1;34m";
+	fi
+fi
 #================================
 #====   Basic functions  ========
-function yes_no() {
-	local yn text=$1
-	while true; do
-	read -p "${text}" yn
+function confirm() {
+	local yn;
+	while true; do read -p "Confirm (y/n) > " yn
 		case $yn in
-			[Yy]* ) echo "yes"; break ;;
-			[Nn]* ) echo "no"; break ;;
+			Y);&  Yes);&  YES);&  yes);&  y) return 0; ;;
+			N);&  No);&   NO);&   no);&   n) return 1; ;;
 		esac
 	done
 }
 function title() { echo -e "${BLUE_BOLD}# $1 ${RESET}"; }
-function subTitle() { echo -e "${BLUE}## $1 ${RESET}"; }
 function finish() { echo -e "\n${GREEN_BOLD}# Finish!${RESET}\n"; exit 0; }
+function user_abort() { echo -e "\n${YELLOW_BOLD}# Abort by user!${RESET}\n"; exit 0; }
 function warn() { echo -e "${YELLOW_BOLD} warning: ${1} ${RESET}"; }
 function success() { echo -e "${GREEN} success: ${1} ${RESET}"; }
-function error() { echo -e "${RED}  error: ${RED_BOLD}$1${RESET}\n"; exit 1; }
+function error() { echo -e "${RED_BOLD}  error: ${RED}$1${RESET}\n"; exit 1; }
 #================================
 
 #===========================================
-#        M a i n   F u n c t i o n 
+#        M a i n   F u n c t i o n
 #===========================================
 
 DIV_LINE="===============================================";
@@ -50,24 +55,27 @@ echo -e ' /_/    \_\_/ \__, |_|\___|'
 echo -e '               __/ |       '
 echo -e '              |___/        '
 echo -e ''
-echo -e '            Update date: 2017-12-26'
+echo -e '            Update date: 2018-02-27'
 echo -e ''
 echo -e "${BOLD} 1.Concat seg-*-v1-a1.ts you downloaded from avgle"
 echo -e "${BOLD} 2.Convert ts file to mp4 using ffmpeg"
-echo -e "${BOLD} 3.Rename mp4 file followed folder name automatically"
-echo -e "${BOLD} 4.Remove All temporary *.ts files${RESET}"
+echo -e "${BOLD} 3.Rename mp4 file name according to folder it located"
+echo -e "${BOLD} 4.Remove All temporary *.ts files if you don't need them anymore${RESET}"
 echo -e "${DIV_LINE}\n"
 
+# ===========================
 # Checking tools
 [[ -z `which ffmpeg` ]] && error "\"ffmpeg\" is missing! (Ubuntu: sudo apt install ffmpeg)";
 [[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
 
+# ===========================
 # Checking path
 [[ -z "$DIR_NAME" ]] && error "current directory name is empty (dangerous)!";
 
+# ===========================
 # Getting max number
 MAX_NUMBE=$(ls | tr ' ' '\n' | gawk '
-	/seg-([0-9]+)-v1-a1.ts/ {
+	/^seg-([0-9]+)-v1-a1.ts$/ {
 		if(match($1, /seg-([0-9]+)-v1-a1.ts/, result)) {
 			v = result[1] - 0;
 			if(v > max)
@@ -75,47 +83,68 @@ MAX_NUMBE=$(ls | tr ' ' '\n' | gawk '
 		}
 	}
 	END {print max ? max : "NULL"}')
-[[ "$MAX_NUMBE" == "NULL" ]] && error "could not find any seg-*-v1-a1.ts you download from avgle.com";
-title "Found avgle ts files, max ts file number is: ${MAX_NUMBE}"
+[[ "$MAX_NUMBE" == "NULL" ]] && error "could not find any seg-*-v1-a1.ts you download from avgle";
+title "Found avgle ts files, max ts file number is: ${MAX_NUMBE}";
 
+# ===========================
+# Compare max number with expected
+EXPECTED="$1";
+if [[ -n "$EXPECTED" ]]; then
+	[[ "$EXPECTED" != "$MAX_NUMBE" ]] && error "expected max number of video fragments is: ${EXPECTED}";
+	title "expected max number of video fragments is same with actual";
+fi
+
+# ===========================
 # Valid all ts files is under folder
 FILES_OK=true
-for i in $(seq  $MAX_NUMBE); do
-	FNAME="seg-${i}-v1-a1.ts"
+for (( i=1 ; i<=$MAX_NUMBE ; i++ )) do
+	FNAME="seg-${i}-v1-a1.ts";
 	if [[ ! -f "$FNAME" ]]; then
 		warn "$FNAME is missing!";
 		FILES_OK=false
 	fi
 done
 [[ "$FILES_OK" == "false" ]] && error "*.ts files are not completed!"
-title "Validated all *.ts files from avgle.com"
+title "Confirmed all *.ts files are existed"
 
-# Concat ts files
-title "Concatenating ts files ..."
-[[ -f "$ALL_IN_ONE_TS_FILE" ]] && rm $ALL_IN_ONE_TS_FILE -f;
-for i in $(seq  $MAX_NUMBE); do
-	cat "seg-${i}-v1-a1.ts" >> $ALL_IN_ONE_TS_FILE
-	[[ -n `echo ${i} | grep '00$'` ]] && echo "  progress: ${i}/${MAX_NUMBE}";
+# ===========================
+# Concatenating .d.ts files
+title "Concatenating ts files ...";
+if [[ -e "$TEMP_FILE" ]]; then
+	echo -e "\nTemporary file is existed! do you want to delete and continue? ($TEMP_FILE)";
+	confirm || user_abort;
+	rm $TEMP_FILE -f || error "could not delete ${TEMP_FILE}";
+fi
+
+for (( i=1 ; i<=$MAX_NUMBE ; i++ )) do
+	cat "seg-${i}-v1-a1.ts" >> $TEMP_FILE;
+	if [[ "$i" == *00 ]] || [[ "$i" == "$MAX_NUMBE" ]]; then
+		echo -e "  progress: ${BOLD}${i}/${MAX_NUMBE}${RESET}";
+	fi
 done
-title "Concatenated ts files to $ALL_IN_ONE_TS_FILE"
+echo -e "";
+title "Concatenated ts files to $TEMP_FILE"
 
-# Converting ts file
+# ===========================
+# Converting .ts file
 title "Converting ts file to mp4 files ..."
-[[ -f "$TARGET_FILE" ]] && rm "$TARGET_FILE" -f;
-ffmpeg -i "${ALL_IN_ONE_TS_FILE}" -acodec copy -vcodec copy "${TARGET_FILE}"
-title "Converted ts file to ${TARGET_FILE}"
+if [[ -e "$TARGET_FILE" ]]; then
+	echo -e "\nTarget file is existed! do you want to delete and continue? ($TARGET_FILE)";
+	confirm || user_abort;
+	rm $TARGET_FILE -f || error "could not delete ${TARGET_FILE}";
+fi
 
+ffmpeg -i "${TEMP_FILE}" -acodec copy -vcodec copy "${TARGET_FILE}" || error "ffmpeg convert response exception!"
+title "Converted ${TEMP_FILE} file to ${TARGET_FILE}";
+
+# ===========================
 # Deleting files
-echo -e ""
-SURE_RM=$(yes_no "Do you want to deleting *.ts files?[y/n]")
-[[ "$SURE_RM" == "no" ]] && finish
+echo -e "\nDo you want to delete temporarty files (included *.d.ts)?";
+confirm || finish
 
 title "Deleting seg-*-v1-a1.ts files ..."
-for i in $(seq  $MAX_NUMBE); do
-	rm "seg-${i}-v1-a1.ts" -f
-done
-rm av.ts -f
-title "Deleted!"
-
+for (( i=1 ; i<=$MAX_NUMBE ; i++ )) do rm "seg-${i}-v1-a1.ts" -f; done
+rm av.ts -f;
+title "All temporary files are deleted!"
 
 finish
