Optimize bash scripts (reference from: mywarr/chrome-avgle-helper)
1. add user-agent HTTP header for download (from @mywarr)
2. add ffmpeg opts `-bsf:a aac_adtstoasc` (from @mywarr)
3. `rm file -f` => `rm -f file` (from @mywarr)
4. check dependencies before the main process of scripts
5. check existance of m3u8 file before merge
6. better `confirm` function  in `Avgle` script

Reference repo: <https://github.com/mywarr/chrome-avgle-helper>

diff --git a/Avgle b/Avgle
--- a/Avgle
+++ b/Avgle
@@ -28,8 +28,8 @@ function confirm() {
 	local yn;
 	while true; do read -p "Confirm (y/n) > " yn
 		case $yn in
-			Y);&  Yes);&  YES);&  yes);&  y) return 0; ;;
-			N);&  No);&   NO);&   no);&   n) return 1; ;;
+			Y|Yes|YES|yes|y) return 0 ;;
+			N|No|NO|no|n) return 1 ;;
 		esac
 	done
 }
@@ -56,7 +56,7 @@ echo -e ' /_/    \_\_/ \__, |_|\___|'
 echo -e '               __/ |       '
 echo -e '              |___/        '
 echo -e ''
-echo -e '            Update date: 2018-04-06'
+echo -e '            Update date: 2018-06-13'
 echo -e ''
 echo -e "${BOLD} 1.Concat seg-*-v1-a1.ts you downloaded from avgle"
 echo -e "${BOLD} 2.Convert ts file to mp4 using ffmpeg"
@@ -65,9 +65,10 @@ echo -e "${BOLD} 4.Remove All temporary *.ts files if you don't need them anymor
 echo -e "${DIV_LINE}\n"
 
 # ===========================
-# Checking tools
+# Checking dependencies
 [[ -z `which ffmpeg` ]] && error "\"ffmpeg\" is missing! (Ubuntu: sudo apt install ffmpeg)";
 [[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
+[[ -z `which sed` ]] && error "\"sed\" is missing! (Ubuntu: sudo apt install sed)";
 
 # ===========================
 # Checking path
@@ -114,11 +115,15 @@ title "Generate concat file for ffmpeg ...";
 if [[ -e "$TEMP_FILE" ]]; then
 	echo -e "\nTemporary file is existed! do you want to delete and continue? ($TEMP_FILE)";
 	confirm || user_abort;
-	rm $TEMP_FILE -f || error "could not delete ${TEMP_FILE}";
+	rm -f $TEMP_FILE || error "could not delete ${TEMP_FILE}";
 fi
 
+# ===========================
+# check is m3u8 list file existed
+[[ -f "$M3U8_FILE" ]] || error "m3u8 play list file \"$M3U8_FILE\" is not existed!";
+
 # Do not actually concat the file, just generate concat file for ffmpeg
-cp $M3U8_FILE $TEMP_FILE
+cp "$M3U8_FILE" "$TEMP_FILE";
 sed -i -e '/^#/d' -e 's:^http.*mp4/:file :g' $TEMP_FILE
 echo -e "";
 title "Concat file $TEMP_FILE generated"
@@ -129,12 +134,17 @@ title "Converting ts file to mp4 files ..."
 if [[ -e "$TARGET_FILE" ]]; then
 	echo -e "\nTarget file is existed! do you want to delete and continue? ($TARGET_FILE)";
 	confirm || user_abort;
-	rm $TARGET_FILE -f || error "could not delete ${TARGET_FILE}";
+	rm -f $TARGET_FILE || error "could not delete ${TARGET_FILE}";
 fi
 
 # -f concat can be performed in ffmpeg, reduce disk usage and time
 # -c copy is equal to -acodec copy -vcodec copy, we just don't want to re-encode the file
-ffmpeg -f concat -i "${TEMP_FILE}" -c copy "${TARGET_FILE}" || error "ffmpeg convert response exception!"
+# -bsf: Bitstream Filters  -bsf:a audio stream filter
+# aac_adtstoasc: https://ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc
+#   Convert MPEG-2/4 AAC ADTS to an MPEG-4 Audio Specific Configuration bitstream.
+#   Reference from repo: https://github.com/mywarr/chrome-avgle-helper
+ffmpeg -f concat -i "${TEMP_FILE}" -bsf:a aac_adtstoasc -c copy "${TARGET_FILE}" \
+	|| error "ffmpeg convert response exception!"
 title "Converted ${TEMP_FILE} file to ${TARGET_FILE}";
 
 # ===========================
@@ -143,8 +153,8 @@ echo -e "\nDo you want to delete temporarty files (included *.d.ts)?";
 confirm || finish
 
 title "Deleting seg-*-v1-a1.ts files ..."
-for (( i=1 ; i<=$MAX_NUMBE ; i++ )) do rm "seg-${i}-v1-a1.ts" -f; done
-rm "${TEMP_FILE}" -f;
+for (( i=1 ; i<=$MAX_NUMBE ; i++ )) do rm -f "seg-${i}-v1-a1.ts"; done
+rm -f "${TEMP_FILE}";
 title "All temporary files are deleted!"
 
 finish
diff --git a/AvgleDownloader b/AvgleDownloader
--- a/AvgleDownloader
+++ b/AvgleDownloader
@@ -7,6 +7,11 @@
 # Add this referer for fix forbidden download action on CDN
 HTTP_REFERER="https://avgle.com"
 
+# The idea why add user-agent header is from fork repository by [mywarr](https://github.com/mywarr)
+# And the following User-Agent is reference from: (Last updated: Tue, 12 Jun 2018 18:38:12 +0000)
+# https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
+HTTP_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36";
+
 #================================
 #====   Colorized variables  ====
 if [[ -t 1 ]]; then # is terminal?
@@ -32,8 +37,8 @@ function confirm() {
 	local yn;
 	while true; do read -p "Confirm (y/n) > " yn
 		case $yn in
-			Y|Yes|YES|yes|y) return 0; ;;
-			N|No|NO|no|n) return 1; ;;
+			Y|Yes|YES|yes|y) return 0 ;;
+			N|No|NO|no|n) return 1 ;;
 		esac
 	done
 }
@@ -54,7 +59,8 @@ function better_wget() {
 	local extra_opts="";
 	if [[ -n "$3" ]]; then extra_opts="-O $3"; fi
 
-	wget --header "Referer: $HTTP_REFERER" $2 $extra_opts || error "Could not download $1";
+	wget --header "Referer: $HTTP_REFERER" --header "User-Agent: $HTTP_USER_AGENT" \
+		$2 $extra_opts || error "Could not download $1";
 }
 
 
@@ -71,12 +77,19 @@ echo -e ' | | | |/ _ \ \ /\ / / '\''_ \| |/ _ \ / _` |/ _` |/ _ \ '\''__|'
 echo -e ' | |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   '
 echo -e ' |____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   '
 echo -e ''
-echo -e '            Update date: 2018-06-01'
+echo -e '            Update date: 2018-06-13'
 echo -e ''
 echo -e "${BOLD} Usage: AvgleDownloader <video-name> <m3u8-url-base64>${RESET}"
 echo -e ''
 echo -e "${DIV_LINE}\n"
 
+# ===========================
+# Checking dependencies
+[[ -z `which wget` ]] && error "\"wget\" is missing! (Ubuntu: sudo apt install wget)";
+[[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
+
+# ===========================
+# Checking arguments
 [[ -z "$1" ]] && error "usage: AvgleDownloader <video-name> <m3u8-url-base64>";
 [[ -z "$2" ]] && error "usage: AvgleDownloader <video-name> <m3u8-url-base64>";
 
@@ -105,7 +118,7 @@ if [[ ! -f "${M3U8_FILE}" ]]; then
 fi
 
 # get total file count:
-function getLastVideoFragment() { cat "$M3U8_FILE" | awk '!/^#/ {print $0}' | tail -n1; }
+function getLastVideoFragment() { cat "$M3U8_FILE" | gawk '!/^#/ {print $0}' | tail -n1; }
 LAST_FRAGMENT_URL=`getLastVideoFragment`;
 
 LAST_FRAGMENT="${LAST_FRAGMENT_URL##*/}";
@@ -143,7 +156,7 @@ if [[ "$MISSING_FILE_COUNT" == "0" ]]; then
 fi
 
 function getBetterFileList() {
-	echo -e "$1" | awk '
+	echo -e "$1" | gawk '
 	function printRange() {
 		if(i!=from) print "{" from ".." i "}";
 		else print from;
