update scripts
1. less ffmpeg log
2. try again without 'referer' header after download file failed

diff --git a/AvgleDownloader b/AvgleDownloader
--- a/AvgleDownloader
+++ b/AvgleDownloader
@@ -6,6 +6,8 @@
 
 # Add this referer for fix forbidden download action on CDN
 HTTP_REFERER="https://avgle.com"
+# enable referer header by default, but it will be turn off (false) after download first file failed.
+ENABLE_REFERER=true
 
 # The idea why add user-agent header is from fork repository by [mywarr](https://github.com/mywarr)
 # And the following User-Agent is reference from: (Last updated: Tue, 12 Jun 2018 18:38:12 +0000)
@@ -56,11 +58,23 @@ function error() { echo -e "${RED_BOLD}  error: ${RED}$1${RESET}\n"; exit 1; }
 # $2: url
 # $3: [Optional] target file
 function better_wget() {
-	local extra_opts="";
-	if [[ -n "$3" ]]; then extra_opts="-O $3"; fi
+	local download_ok=true;
 
-	wget --header "Referer: $HTTP_REFERER" --header "User-Agent: $HTTP_USER_AGENT" \
-		$2 $extra_opts || error "Could not download $1";
+	local extra_opts="";
+	[[ -n "$3" ]] && extra_opts="-O $3";
+
+	if [[ $ENABLE_REFERER == true ]]; then
+		wget --header "Referer: $HTTP_REFERER" --header "User-Agent: $HTTP_USER_AGENT" \
+			$2 $extra_opts || download_ok=false;
+
+		if [[ $download_ok != true ]]; then
+			warn "execute wget with 'Referer' header failed! (trying to execute again without 'Referer' header)";
+			ENABLE_REFERER=false;
+			wget --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
+		fi
+	else
+		wget --header "User-Agent: $HTTP_USER_AGENT" $2 $extra_opts || error "Could not download $1";
+	fi
 }
 
 
@@ -77,7 +91,7 @@ echo -e ' | | | |/ _ \ \ /\ / / '\''_ \| |/ _ \ / _` |/ _` |/ _ \ '\''__|'
 echo -e ' | |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   '
 echo -e ' |____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   '
 echo -e ''
-echo -e '            Update date: 2018-06-13'
+echo -e '            Update date: 2018-10-12'
 echo -e ''
 echo -e "${BOLD} Usage: AvgleDownloader <video-name> <m3u8-url-base64>${RESET}"
 echo -e ''
